compress_assets: off
gzip_assets: off

javascripts:
  assets:
    - public/javascripts/jquery-1.7.min.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/json2.js
    - public/javascripts/jquery.tmpl.js
    - app/client/lib/models/*.js
    - app/client/lib/views/*.js
    - app/client/lib/controllers/*.js
    - app/client/lib/templates/**/*.js
    - app/client/lib/app.js

