compress_assets: off
gzip_assets: off
template_extension: html

javascripts:
  assets:
    - public/javascripts/vendor/jquery-1.7.min.js
    - public/javascripts/vendor/underscore.js
    - public/javascripts/vendor/backbone.js
    - public/javascripts/vendor/json2.js
    - public/javascripts/vendor/jquery.tmpl.js
    - app/lib/client/models/*.js
    - app/lib/client/views/*.js
    - app/src/client/templates/**/*.html
    - app/lib/client/app.js

